using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBrewerySkuTemps
{
    public class TbBrewerySkuTempManager : TbBrewerySkuTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBrewerySkuTempManager(ITbBrewerySkuTempRepository tbBrewerySkuTempRepository)
            : base(tbBrewerySkuTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}