using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbPersons
{
    public class TbPersonManager : TbPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbPersonManager(ITbPersonRepository tbPersonRepository)
            : base(tbPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}