using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyInvestTemps
{
    public class TbCompanyInvestTempManager : TbCompanyInvestTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyInvestTempManager(ITbCompanyInvestTempRepository tbCompanyInvestTempRepository)
            : base(tbCompanyInvestTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}