using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyTemps
{
    public class TbCompanyTempManager : TbCompanyTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyTempManager(ITbCompanyTempRepository tbCompanyTempRepository)
            : base(tbCompanyTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}