using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbInfoUpdates
{
    public class TbInfoUpdateManager : TbInfoUpdateManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbInfoUpdateManager(ITbInfoUpdateRepository tbInfoUpdateRepository)
            : base(tbInfoUpdateRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}