using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbInfoUpdates
{
    public class TbInfoUpdate : TbInfoUpdateBase
    {
        //<suite-custom-code-autogenerated>
        public TbInfoUpdate()
        {

        }

        public TbInfoUpdate(string tableName, string columnName, int screenId, int rowId, string command, int isActive, bool isVisible, string? screenName = null, string? groupName = null, string? lastValue = null, string? newValue = null, byte? docStatus = null, string? comment = null, int? crt_user = null, DateTime? crt_date = null, int? mod_user = null, DateTime? mod_date = null, Guid? changeSetId = null, DateTime? timeAssessment = null)
            : base(tableName, columnName, screenId, rowId, command, isActive, isVisible, screenName, groupName, lastValue, newValue, docStatus, comment, crt_user, crt_date, mod_user, mod_date, changeSetId, timeAssessment)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}