using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisCompanies
{
    public class TbHisCompanyManager : TbHisCompanyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisCompanyManager(ITbHisCompanyRepository tbHisCompanyRepository)
            : base(tbHisCompanyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}