using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbHisBreweries
{
    public class TbHisBrewery : TbHisBreweryBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisBrewery()
        {

        }

        public TbHisBrewery(DateTime insertDate, int type, int idBrewery, string breweryName, int companyId, bool? isSendMail = null, DateTime? dateSendMail = null, string? breweryName_EN = null, string? breweryAdress = null, string? briefName = null, decimal? capacityVolume = null, decimal? deliveryVolume = null, string? note = null, byte? docStatus = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(insertDate, type, idBrewery, breweryName, companyId, isSendMail, dateSendMail, breweryName_EN, breweryAdress, briefName, capacityVolume, deliveryVolume, note, docStatus, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}