using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TsClasses
{
    public class TsClass : TsClassBase
    {
        //<suite-custom-code-autogenerated>
        public TsClass()
        {

        }

        public TsClass(string parentCode, string code, string? name = null, string? name_EN = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null, string? code_Type = null)
            : base(parentCode, code, name, name_EN, isActive, crt_date, crt_user, mod_date, mod_user, code_Type)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}