using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TsClasses
{
    public class TsClassManager : TsClassManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TsClassManager(ITsClassRepository tsClassRepository)
            : base(tsClassRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}