using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyPersonTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyPersonTemps
{
    public class TbCompanyPersonTempsAppService : TbCompanyPersonTempsAppServiceBase, ITbCompanyPersonTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyPersonTempsAppService(ITbCompanyPersonTempRepository tbCompanyPersonTempRepository, TbCompanyPersonTempManager tbCompanyPersonTempManager, IDistributedCache<TbCompanyPersonTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyPersonTempRepository, tbCompanyPersonTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyPersonTempDto>> GetListNoPagedAsync(GetTbCompanyPersonTempsInput input)
        {
            var items = await _tbCompanyPersonTempRepository.GetListNoPagedAsync(input.FilterText, input.idCompanyPersonMin, input.idCompanyPersonMax, input.BranchCode, input.CompanyIdMin, input.CompanyIdMax, input.PersonIdMin, input.PersonIdMax, input.PositionIdMin, input.PositionIdMax, input.FromDateMin, input.FromDateMax, input.ToDateMin, input.ToDateMax, input.PositionTypeMin, input.PositionTypeMax, input.PositionCode, input.PersonalValueMin, input.PersonalValueMax, input.PersonalSharePercentageMin, input.PersonalSharePercentageMax, input.OwnerValueMin, input.OwnerValueMax, input.RepresentativePercentageMin, input.RepresentativePercentageMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyPersonTemp>, List<TbCompanyPersonTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}