using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisPersons
{
    public class TbHisPersonManager : TbHisPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisPersonManager(ITbHisPersonRepository tbHisPersonRepository)
            : base(tbHisPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}