using Sabeco_Factsheet.TbCompanyStocks;
using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;  
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyStocks
{
    public class TbCompanyStocksAppService : TbCompanyStocksAppServiceBase, ITbCompanyStocksAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyStocksAppService(ITbCompanyStockRepository tbCompanyStockRepository, TbCompanyStockManager tbCompanyStockManager, IDistributedCache<TbCompanyStockDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyStockRepository, tbCompanyStockManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyStockDto>> GetListNoPagedAsync(GetTbCompanyStocksInput input)
        {
            var items = await _tbCompanyStockRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.CompanyCode, input.IsPublicCompany, input.StockExchange, input.RegistrationDateMin, input.RegistrationDateMax, input.CharteredCapitalMin, input.CharteredCapitalMax, input.ParValueMin, input.ParValueMax, input.TotalShareMin, input.TotalShareMax, input.ListedShareMin, input.ListedShareMax, input.Description, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyStock>, List<TbCompanyStockDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}