using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbHisBreweryDeliveryVolumes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbHisBreweryDeliveryVolumes
{
    public class TbHisBreweryDeliveryVolumesAppService : TbHisBreweryDeliveryVolumesAppServiceBase, ITbHisBreweryDeliveryVolumesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbHisBreweryDeliveryVolumesAppService(ITbHisBreweryDeliveryVolumeRepository tbHisBreweryDeliveryVolumeRepository, TbHisBreweryDeliveryVolumeManager tbHisBreweryDeliveryVolumeManager, IDistributedCache<TbHisBreweryDeliveryVolumeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbHisBreweryDeliveryVolumeRepository, tbHisBreweryDeliveryVolumeManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbHisBreweryDeliveryVolumeDto>> GetListNoPagedAsync(GetTbHisBreweryDeliveryVolumesInput input)
        {
            var items = await _tbHisBreweryDeliveryVolumeRepository.GetListNoPagedAsync(input.FilterText, input.IsSendMail, input.DateSendMailMin, input.DateSendMailMax, input.InsertDateMin, input.InsertDateMax, input.TypeMin, input.TypeMax, input.IdBreweryDeliveryVolumeMin, input.IdBreweryDeliveryVolumeMax, input.BreweryIdMin, input.BreweryIdMax, input.BreweryCode, input.YearMin, input.YearMax, input.DeliveryVolumeMin, input.DeliveryVolumeMax, input.isActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbHisBreweryDeliveryVolume>, List<TbHisBreweryDeliveryVolumeDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}