using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBreweryDeliveryVolumes
{
    public class TbBreweryDeliveryVolumeManager : TbBreweryDeliveryVolumeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryDeliveryVolumeManager(ITbBreweryDeliveryVolumeRepository tbBreweryDeliveryVolumeRepository)
            : base(tbBreweryDeliveryVolumeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}