using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbBreweryDeliveryVolumes
{
    public class TbBreweryDeliveryVolume : TbBreweryDeliveryVolumeBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryDeliveryVolume()
        {

        }

        public TbBreweryDeliveryVolume(int? breweryId = null, string? breweryCode = null, int? year = null, decimal? deliveryVolume = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(breweryId, breweryCode, year, deliveryVolume, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}