using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBranchTemps
{
    public class TbCompanyBranchTempManager : TbCompanyBranchTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchTempManager(ITbCompanyBranchTempRepository tbCompanyBranchTempRepository)
            : base(tbCompanyBranchTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}