using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyBranchTemps
{
    public class TbCompanyBranchTemp : TbCompanyBranchTempBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchTemp()
        {

        }

        public TbCompanyBranchTemp(int? companyId = null, string? branchName = null, string? branchAddress = null, string? branchCode = null, string? contactPerson = null, string? contactPhone = null, string? email = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(companyId, branchName, branchAddress, branchCode, contactPerson, contactPhone, email, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}