using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLogPrintings
{
    public class TbLogPrinting : TbLogPrintingBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogPrinting()
        {

        }

        public TbLogPrinting(string? userName = null, string? companyCode = null, string? fileLanguage = null, bool? isPrinting = null, DateTime? printTime = null)
            : base(userName, companyCode, fileLanguage, isPrinting, printTime)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}