using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogPrintings
{
    public class TbLogPrintingManager : TbLogPrintingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogPrintingManager(ITbLogPrintingRepository tbLogPrintingRepository)
            : base(tbLogPrintingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}