using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogPrintings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogPrintings
{
    public class TbLogPrintingsAppService : TbLogPrintingsAppServiceBase, ITbLogPrintingsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogPrintingsAppService(ITbLogPrintingRepository tbLogPrintingRepository, TbLogPrintingManager tbLogPrintingManager, IDistributedCache<TbLogPrintingDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogPrintingRepository, tbLogPrintingManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogPrintingDto>> GetListNoPagedAsync(GetTbLogPrintingsInput input)
        {
            var items = await _tbLogPrintingRepository.GetListNoPagedAsync(input.FilterText, input.userName, input.companyCode, input.fileLanguage, input.isPrinting, input.printTimeMin, input.printTimeMax, input.Sorting);

            return ObjectMapper.Map<List<TbLogPrinting>, List<TbLogPrintingDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}