using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbInvests
{
    public class TbInvestManager : TbInvestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbInvestManager(ITbInvestRepository tbInvestRepository)
            : base(tbInvestRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}