using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbInvests
{
    public class TbInvest : TbInvestBase
    {
        //<suite-custom-code-autogenerated>
        public TbInvest()
        {

        }

        public TbInvest(string branchCode, string companyCode, bool isDeleted, int? branchId = null, int? companyId = null, int? shareNumTotal = null, decimal? shareValueTotal = null, string? note = null, byte? docStatus = null, bool? investGroup = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(branchCode, companyCode, isDeleted, branchId, companyId, shareNumTotal, shareValueTotal, note, docStatus, investGroup, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}