using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyPersons;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyPersons
{
    public class TbCompanyPersonsAppService : TbCompanyPersonsAppServiceBase, ITbCompanyPersonsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyPersonsAppService(ITbCompanyPersonRepository tbCompanyPersonRepository, TbCompanyPersonManager tbCompanyPersonManager, IDistributedCache<TbCompanyPersonDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyPersonRepository, tbCompanyPersonManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyPersonDto>> GetListNoPagedAsync(GetTbCompanyPersonsInput input)
        {
            var items = await _tbCompanyPersonRepository.GetListNoPagedAsync(input.FilterText, input.BranchCode, input.CompanyIdMin, input.CompanyIdMax, input.PersonIdMin, input.PersonIdMax, input.PositionIdMin, input.PositionIdMax, input.FromDateMin, input.FromDateMax, input.ToDateMin, input.ToDateMax, input.PositionCode, input.PostionTypeMin, input.PostionTypeMax, input.PersonalValueMin, input.PersonalValueMax, input.PersonalSharePercentageMin, input.PersonalSharePercentageMax, input.OwnerValueMin, input.OwnerValueMax, input.RepresentativePercentageMin, input.RepresentativePercentageMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyPerson>, List<TbCompanyPersonDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public virtual async Task<List<TbCompanyPersonDto>> GetListByCompanyId(int id)
        {
            var items = await _tbCompanyPersonRepository.GetListByCompanyId(id);
            return ObjectMapper.Map<List<TbCompanyPerson>, List<TbCompanyPersonDto>>(items);
        }
    }
}