using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBreweryTemps
{
    public class TbBreweryTempManager : TbBreweryTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryTempManager(ITbBreweryTempRepository tbBreweryTempRepository)
            : base(tbBreweryTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}