using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbBreweryTemps
{
    public class TbBreweryTemp : TbBreweryTempBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryTemp()
        {

        }

        public TbBreweryTemp(int idBrewery, string breweryCode, string breweryName, int companyId, string? breweryName_EN = null, string? briefName = null, string? breweryAdress = null, decimal? capacityVolume = null, decimal? deliveryVolume = null, string? note = null, byte? docStatus = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(idBrewery, breweryCode, breweryName, companyId, breweryName_EN, briefName, breweryAdress, capacityVolume, deliveryVolume, note, docStatus, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}