using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbPersons;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbPersons
{
    public class TbPersonsAppService : TbPersonsAppServiceBase, ITbPersonsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbPersonsAppService(ITbPersonRepository tbPersonRepository, TbPersonManager tbPersonManager, IDistributedCache<TbPersonDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbPersonRepository, tbPersonManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbPersonDto>> GetListNoPagedAsync(GetTbPersonsInput input)
        {
            var items = await _tbPersonRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.CompanyIdMin, input.CompanyIdMax, input.FullName, input.BirthDateMin, input.BirthDateMax, input.BirthPlace, input.Address, input.IDCardNo, input.IDCardDateMin, input.IDCardDateMax, input.IdCardIssuePlace, input.Ethnicity, input.Religion, input.NationalityCode, input.Gender, input.Phone, input.Email, input.Note, input.Image, input.IsActive, input.DocStatusMin, input.DocStatusMax, input.IsCheckRetirement, input.IsCheckTermEnd, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.OldCode, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbPerson>, List<TbPersonDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}