using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbAssets
{
    public class TbAsset : TbAssetBase
    {
        //<suite-custom-code-autogenerated>
        public TbAsset()
        {

        }

        public TbAsset(int companyId, bool isDeleted, string? assetType = null, string? assetItem = null, string? assetAddress = null, decimal? quantity = null, string? docNo = null, DateTime? docDate = null, DateTime? expireDate = null, string? description = null, byte? docStatus = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(companyId, isDeleted, assetType, assetItem, assetAddress, quantity, docNo, docDate, expireDate, description, docStatus, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}