using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbAssets
{
    public class TbAssetManager : TbAssetManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbAssetManager(ITbAssetRepository tbAssetRepository)
            : base(tbAssetRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}