using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyInvestTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyInvestTemps
{
    public class TbCompanyInvestTempsAppService : TbCompanyInvestTempsAppServiceBase, ITbCompanyInvestTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyInvestTempsAppService(ITbCompanyInvestTempRepository tbCompanyInvestTempRepository, TbCompanyInvestTempManager tbCompanyInvestTempManager, IDistributedCache<TbCompanyInvestTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyInvestTempRepository, tbCompanyInvestTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyInvestTempDto>> GetListNoPagedAsync(GetTbCompanyInvestTempsInput input)
        {
            var items = await _tbCompanyInvestTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.CompanyName, input.SharesMin, input.SharesMax, input.HoldingMin, input.HoldingMax, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyInvestTemp>, List<TbCompanyInvestTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}