using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbUserMappingCompanies
{
    public class TbUserMappingCompany : TbUserMappingCompanyBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingCompany()
        {

        }

        public TbUserMappingCompany(int? userid = null, int? companyid = null, bool? isActive = null)
            : base(userid, companyid, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}