using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbUserMappingCompanies
{
    public class TbUserMappingCompanyManager : TbUserMappingCompanyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingCompanyManager(ITbUserMappingCompanyRepository tbUserMappingCompanyRepository)
            : base(tbUserMappingCompanyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}