using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisBreweryDeliveryVolumes
{
    public class TbHisBreweryDeliveryVolumeManager : TbHisBreweryDeliveryVolumeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisBreweryDeliveryVolumeManager(ITbHisBreweryDeliveryVolumeRepository tbHisBreweryDeliveryVolumeRepository)
            : base(tbHisBreweryDeliveryVolumeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}