using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbPersonTemps
{
    public class TbPersonTempManager : TbPersonTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbPersonTempManager(ITbPersonTempRepository tbPersonTempRepository)
            : base(tbPersonTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}