using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyMajors
{
    public class TbCompanyMajorManager : TbCompanyMajorManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMajorManager(ITbCompanyMajorRepository tbCompanyMajorRepository)
            : base(tbCompanyMajorRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}