using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogSendEmails
{
    public class TbLogSendEmailManager : TbLogSendEmailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogSendEmailManager(ITbLogSendEmailRepository tbLogSendEmailRepository)
            : base(tbLogSendEmailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}