using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBranchTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBranchTemps
{
    public class TbCompanyBranchTempsAppService : TbCompanyBranchTempsAppServiceBase, ITbCompanyBranchTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchTempsAppService(ITbCompanyBranchTempRepository tbCompanyBranchTempRepository, TbCompanyBranchTempManager tbCompanyBranchTempManager, IDistributedCache<TbCompanyBranchTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBranchTempRepository, tbCompanyBranchTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBranchTempDto>> GetListNoPagedAsync(GetTbCompanyBranchTempsInput input)
        {
            var items = await _tbCompanyBranchTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.BranchName, input.BranchAddress, input.BranchCode, input.ContactPerson, input.ContactPhone, input.Email, input.isActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBranchTemp>, List<TbCompanyBranchTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}