using Sabeco_Factsheet.TbUserMappingPersons;
using Xunit;

namespace Sabeco_Factsheet.EntityFrameworkCore.Applications.TbUserMappingPersons;

public class EfCoreTbUserMappingPersonsAppServiceTests : TbUserMappingPersonsAppServiceTests<Sabeco_FactsheetEntityFrameworkCoreTestModule>
{
}