using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBrewerySkus
{
    public class TbBrewerySkuManager : TbBrewerySkuManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBrewerySkuManager(ITbBrewerySkuRepository tbBrewerySkuRepository)
            : base(tbBrewerySkuRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}