using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBreweryDeliveryVolumeTemps
{
    public class TbBreweryDeliveryVolumeTempManager : TbBreweryDeliveryVolumeTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryDeliveryVolumeTempManager(ITbBreweryDeliveryVolumeTempRepository tbBreweryDeliveryVolumeTempRepository)
            : base(tbBreweryDeliveryVolumeTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}