using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbFileUploads
{
    public class TbFileUpload : TbFileUploadBase
    {
        //<suite-custom-code-autogenerated>
        public TbFileUpload()
        {

        }

        public TbFileUpload(int downloadCount, int? companyId = null, int? personId = null, string? fileName = null, string? fullFileName = null, string? fileLink = null, DateTime? uploadDate = null, int? userUpload = null, string? note = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(downloadCount, companyId, personId, fileName, fullFileName, fileLink, uploadDate, userUpload, note, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}