using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbFileUploads
{
    public class TbFileUploadManager : TbFileUploadManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbFileUploadManager(ITbFileUploadRepository tbFileUploadRepository)
            : base(tbFileUploadRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}