using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLogExportDatas
{
    public class TbLogExportData : TbLogExportDataBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogExportData()
        {

        }

        public TbLogExportData(DateTime timeExport, bool isSuccess, int userExport, string? tableName = null, string? reasonExportFailed = null)
            : base(timeExport, isSuccess, userExport, tableName, reasonExportFailed)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}