using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogExportDatas
{
    public class TbLogExportDataManager : TbLogExportDataManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogExportDataManager(ITbLogExportDataRepository tbLogExportDataRepository)
            : base(tbLogExportDataRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}