using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbUserMappingCompanies;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbUserMappingCompanies
{
    public class TbUserMappingCompaniesAppService : TbUserMappingCompaniesAppServiceBase, ITbUserMappingCompaniesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingCompaniesAppService(ITbUserMappingCompanyRepository tbUserMappingCompanyRepository, TbUserMappingCompanyManager tbUserMappingCompanyManager, IDistributedCache<TbUserMappingCompanyDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbUserMappingCompanyRepository, tbUserMappingCompanyManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbUserMappingCompanyDto>> GetListNoPagedAsync(GetTbUserMappingCompaniesInput input)
        {
            var items = await _tbUserMappingCompanyRepository.GetListNoPagedAsync(input.FilterText, input.useridMin, input.useridMax, input.companyidMin, input.companyidMax, input.IsActive, input.Sorting);

            return ObjectMapper.Map<List<TbUserMappingCompany>, List<TbUserMappingCompanyDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}