using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbHisCompanyPersons
{
    public class TbHisCompanyPerson : TbHisCompanyPersonBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisCompanyPerson()
        {

        }

        public TbHisCompanyPerson(int type, int idCompanyPerson, int companyId, int personId, bool isActive, bool? isSendMail = null, DateTime? dateSendMail = null, DateTime? insertDate = null, string? branchCode = null, DateTime? fromDate = null, DateTime? toDate = null, int? positionId = null, string? positionCode = null, decimal? personalValue = null, decimal? personalSharePercentage = null, decimal? ownerValue = null, decimal? representativePercentage = null, string? note = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(type, idCompanyPerson, companyId, personId, isActive, isSendMail, dateSendMail, insertDate, branchCode, fromDate, toDate, positionId, positionCode, personalValue, personalSharePercentage, ownerValue, representativePercentage, note, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}