using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisCompanyPersons
{
    public class TbHisCompanyPersonManager : TbHisCompanyPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisCompanyPersonManager(ITbHisCompanyPersonRepository tbHisCompanyPersonRepository)
            : base(tbHisCompanyPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}