using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TsClassTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TsClassTemps
{
    public class TsClassTempsAppService : TsClassTempsAppServiceBase, ITsClassTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TsClassTempsAppService(ITsClassTempRepository tsClassTempRepository, TsClassTempManager tsClassTempManager, IDistributedCache<TsClassTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tsClassTempRepository, tsClassTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TsClassTempDto>> GetListNoPagedAsync(GetTsClassTempsInput input)
        {
            var items = await _tsClassTempRepository.GetListNoPagedAsync(input.FilterText, input.ParentCode, input.Code, input.Name, input.Name_EN, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Code_Type, input.Sorting);

            return ObjectMapper.Map<List<TsClassTemp>, List<TsClassTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}