using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyMajorTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyMajorTemps
{
    public class TbCompanyMajorTempsAppService : TbCompanyMajorTempsAppServiceBase, ITbCompanyMajorTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMajorTempsAppService(ITbCompanyMajorTempRepository tbCompanyMajorTempRepository, TbCompanyMajorTempManager tbCompanyMajorTempManager, IDistributedCache<TbCompanyMajorTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyMajorTempRepository, tbCompanyMajorTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyMajorTempDto>> GetListNoPagedAsync(GetTbCompanyMajorTempsInput input)
        {
            var items = await _tbCompanyMajorTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.ShareHolderMajor, input.ShareHolderType, input.FromDateMin, input.FromDateMax, input.ToDateMin, input.ToDateMax, input.ShareHolderValueMin, input.ShareHolderValueMax, input.ShareHolderRateMin, input.ShareHolderRateMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.ClassIdMin, input.ClassIdMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyMajorTemp>, List<TbCompanyMajorTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}