using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogExportDatas;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogExportDatas
{
    public class TbLogExportDatasAppService : TbLogExportDatasAppServiceBase, ITbLogExportDatasAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogExportDatasAppService(ITbLogExportDataRepository tbLogExportDataRepository, TbLogExportDataManager tbLogExportDataManager, IDistributedCache<TbLogExportDataDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogExportDataRepository, tbLogExportDataManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogExportDataDto>> GetListNoPagedAsync(GetTbLogExportDatasInput input)
        {
            var items = await _tbLogExportDataRepository.GetListNoPagedAsync(input.FilterText, input.TimeExportMin, input.TimeExportMax, input.IsSuccess, input.UserExportMin, input.UserExportMax, input.TableName, input.ReasonExportFailed, input.Sorting);

            return ObjectMapper.Map<List<TbLogExportData>, List<TbLogExportDataDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}