using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbTimeScripts
{
    public class TbTimeScript : TbTimeScriptBase
    {
        //<suite-custom-code-autogenerated>
        public TbTimeScript()
        {

        }

        public TbTimeScript(string? code = null, int? year = null, int? month = null, int? day = null, int? hour = null, int? minute = null, int? second = null)
            : base(code, year, month, day, hour, minute, second)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}