using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbTimeScripts
{
    public class TbTimeScriptManager : TbTimeScriptManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbTimeScriptManager(ITbTimeScriptRepository tbTimeScriptRepository)
            : base(tbTimeScriptRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}