using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLandInfos
{
    public class TbLandInfo : TbLandInfoBase
    {
        //<suite-custom-code-autogenerated>
        public TbLandInfo()
        {

        }

        public TbLandInfo(int companyId, string typeOfLand, string? description = null, string? address = null, decimal? area = null, string? supportingDocument = null, DateTime? issueDate = null, DateTime? expiryDate = null, string? payment = null, string? remark = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(companyId, typeOfLand, description, address, area, supportingDocument, issueDate, expiryDate, payment, remark, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}