using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLandInfos
{
    public class TbLandInfoManager : TbLandInfoManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLandInfoManager(ITbLandInfoRepository tbLandInfoRepository)
            : base(tbLandInfoRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}