using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBranchs
{
    public class TbCompanyBranchManager : TbCompanyBranchManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchManager(ITbCompanyBranchRepository tbCompanyBranchRepository)
            : base(tbCompanyBranchRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}