using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLogErrors
{
    public class TbLogError : TbLogErrorBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogError()
        {

        }

        public TbLogError(DateTime timeLog, int userLog, string functionLog, string reasonFailed, string? iPAddress = null, string? classLog = null)
            : base(timeLog, userLog, functionLog, reasonFailed, iPAddress, classLog)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}