using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogErrors
{
    public class TbLogErrorManager : TbLogErrorManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogErrorManager(ITbLogErrorRepository tbLogErrorRepository)
            : base(tbLogErrorRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}