using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbNationalityTemps
{
    public class TbNationalityTempManager : TbNationalityTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbNationalityTempManager(ITbNationalityTempRepository tbNationalityTempRepository)
            : base(tbNationalityTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}