using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbContacts
{
    public class TbContactManager : TbContactManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbContactManager(ITbContactRepository tbContactRepository)
            : base(tbContactRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}