using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbContacts
{
    public class TbContact : TbContactBase
    {
        //<suite-custom-code-autogenerated>
        public TbContact()
        {

        }

        public TbContact(int companyid, string contactName, bool isActive, bool isDeleted, string? contactDept = null, string? contactPosition = null, string? contactEmail = null, string? contactPhone = null, string? note = null, byte? docStatus = null, int? crt_user = null, DateTime? crt_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(companyid, contactName, isActive, isDeleted, contactDept, contactPosition, contactEmail, contactPhone, note, docStatus, crt_user, crt_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}