using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbInvests;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbInvests
{
    public class TbInvestsAppService : TbInvestsAppServiceBase, ITbInvestsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbInvestsAppService(ITbInvestRepository tbInvestRepository, TbInvestManager tbInvestManager, IDistributedCache<TbInvestDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbInvestRepository, tbInvestManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbInvestDto>> GetListNoPagedAsync(GetTbInvestsInput input)
        {
            var items = await _tbInvestRepository.GetListNoPagedAsync(input.FilterText, input.BranchCode, input.BranchIdMin, input.BranchIdMax, input.CompanyIdMin, input.CompanyIdMax, input.CompanyCode, input.ShareNumTotalMin, input.ShareNumTotalMax, input.ShareValueTotalMin, input.ShareValueTotalMax, input.Note, input.DocStatusMin, input.DocStatusMax, input.InvestGroup, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbInvest>, List<TbInvestDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}