using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBusinessDetails;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBusinessDetails
{
    public class TbCompanyBusinessDetailsAppService : TbCompanyBusinessDetailsAppServiceBase, ITbCompanyBusinessDetailsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessDetailsAppService(ITbCompanyBusinessDetailRepository tbCompanyBusinessDetailRepository, TbCompanyBusinessDetailManager tbCompanyBusinessDetailManager, IDistributedCache<TbCompanyBusinessDetailDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBusinessDetailRepository, tbCompanyBusinessDetailManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBusinessDetailDto>> GetListNoPagedAsync(GetTbCompanyBusinessDetailsInput input)
        {
            var items = await _tbCompanyBusinessDetailRepository.GetListNoPagedAsync(input.FilterText, input.ParentIdMin, input.ParentIdMax, input.RegistrationCode, input.RegistrationName, input.RegistrationName_EN, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBusinessDetail>, List<TbCompanyBusinessDetailDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}