using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisBrewerySkus
{
    public class TbHisBrewerySkuManager : TbHisBrewerySkuManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisBrewerySkuManager(ITbHisBrewerySkuRepository tbHisBrewerySkuRepository)
            : base(tbHisBrewerySkuRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}