using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbPersonTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbPersonTemps
{
    public class TbPersonTempsAppService : TbPersonTempsAppServiceBase, ITbPersonTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbPersonTempsAppService(ITbPersonTempRepository tbPersonTempRepository, TbPersonTempManager tbPersonTempManager, IDistributedCache<TbPersonTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbPersonTempRepository, tbPersonTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbPersonTempDto>> GetListNoPagedAsync(GetTbPersonTempsInput input)
        {
            var items = await _tbPersonTempRepository.GetListNoPagedAsync(input.FilterText, input.idPersonMin, input.idPersonMax, input.Code, input.CompanyIdMin, input.CompanyIdMax, input.FullName, input.BirthDateMin, input.BirthDateMax, input.BirthPlace, input.Address, input.IDCardNo, input.IDCardDateMin, input.IDCardDateMax, input.IdCardIssuePlace, input.Ethnicity, input.Religion, input.NationalityCode, input.Gender, input.Phone, input.Email, input.Note, input.Image, input.IsActive, input.DocStatusMin, input.DocStatusMax, input.IsCheckRetirement, input.IsCheckTermEnd, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.OldCode, input.Sorting);

            return ObjectMapper.Map<List<TbPersonTemp>, List<TbPersonTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}