using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbUsers
{
    public class TbUser : TbUserBase
    {
        //<suite-custom-code-autogenerated>
        public TbUser()
        {

        }

        public TbUser(string userPrincipalName, string userName, string fullName, bool isActive, string? email = null, int? companyId = null, byte? docStatus = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null, Guid? abpUserId = null)
            : base(userPrincipalName, userName, fullName, isActive, email, companyId, docStatus, crt_date, crt_user, mod_date, mod_user, abpUserId)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}