using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbUsers
{
    public class TbUserManager : TbUserManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserManager(ITbUserRepository tbUserRepository)
            : base(tbUserRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}