using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogLogins
{
    public class TbLogLoginManager : TbLogLoginManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogLoginManager(ITbLogLoginRepository tbLogLoginRepository)
            : base(tbLogLoginRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}