using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLogLogins
{
    public class TbLogLogin : TbLogLoginBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogLogin()
        {

        }

        public TbLogLogin(string iPTracking, string? userName = null, DateTime? loginDate = null, bool? statusLogin = null)
            : base(iPTracking, userName, loginDate, statusLogin)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}