using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbPositions
{
    public class TbPosition : TbPositionBase
    {
        //<suite-custom-code-autogenerated>
        public TbPosition()
        {

        }

        public TbPosition(string code, string name, string name_EN, bool isActive, bool isDeleted, byte? positionType = null, int? crt_user = null, DateTime? ctr_date = null, int? mod_user = null, DateTime? mod_date = null, int? orderNumb = null)
            : base(code, name, name_EN, isActive, isDeleted, positionType, crt_user, ctr_date, mod_user, mod_date, orderNumb)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}