using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbPositions
{
    public class TbPositionManager : TbPositionManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbPositionManager(ITbPositionRepository tbPositionRepository)
            : base(tbPositionRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}