using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBreweryImages
{
    public class TbBreweryImageManager : TbBreweryImageManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryImageManager(ITbBreweryImageRepository tbBreweryImageRepository)
            : base(tbBreweryImageRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}