using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogErrors;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogErrors
{
    public class TbLogErrorsAppService : TbLogErrorsAppServiceBase, ITbLogErrorsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogErrorsAppService(ITbLogErrorRepository tbLogErrorRepository, TbLogErrorManager tbLogErrorManager, IDistributedCache<TbLogErrorDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogErrorRepository, tbLogErrorManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogErrorDto>> GetListNoPagedAsync(GetTbLogErrorsInput input)
        {
            var items = await _tbLogErrorRepository.GetListNoPagedAsync(input.FilterText, input.TimeLogMin, input.TimeLogMax, input.UserLogMin, input.UserLogMax, input.IPAddress, input.ClassLog, input.FunctionLog, input.ReasonFailed, input.Sorting);

            return ObjectMapper.Map<List<TbLogError>, List<TbLogErrorDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}