using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogLogins;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogLogins
{
    public class TbLogLoginsAppService : TbLogLoginsAppServiceBase, ITbLogLoginsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogLoginsAppService(ITbLogLoginRepository tbLogLoginRepository, TbLogLoginManager tbLogLoginManager, IDistributedCache<TbLogLoginDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogLoginRepository, tbLogLoginManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogLoginDto>> GetListNoPagedAsync(GetTbLogLoginsInput input)
        {
            var items = await _tbLogLoginRepository.GetListNoPagedAsync(input.FilterText, input.UserName, input.LoginDateMin, input.LoginDateMax, input.IPTracking, input.StatusLogin, input.Sorting);

            return ObjectMapper.Map<List<TbLogLogin>, List<TbLogLoginDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}