using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbBranchs;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbBranchs
{
    public class TbBranchsAppService : TbBranchsAppServiceBase, ITbBranchsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbBranchsAppService(ITbBranchRepository tbBranchRepository, TbBranchManager tbBranchManager, IDistributedCache<TbBranchDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbBranchRepository, tbBranchManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbBranchDto>> GetListNoPagedAsync(GetTbBranchsInput input)
        {
            var items = await _tbBranchRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.BriefName, input.Name, input.Name_EN, input.CompanyCode, input.Description, input.IsActive, input.Crt_DateMin, input.Crt_DateMax, input.Sorting);

            return ObjectMapper.Map<List<TbBranch>, List<TbBranchDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}