using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbConfigRetirementTimes
{
    public class TbConfigRetirementTimeManager : TbConfigRetirementTimeManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbConfigRetirementTimeManager(ITbConfigRetirementTimeRepository tbConfigRetirementTimeRepository)
            : base(tbConfigRetirementTimeRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}