using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbConfigRetirementTimes
{
    public class TbConfigRetirementTime : TbConfigRetirementTimeBase
    {
        //<suite-custom-code-autogenerated>
        public TbConfigRetirementTime()
        {

        }

        public TbConfigRetirementTime(string? code = null, int? yearNumb = null, int? monthNumb = null, int? dayNumb = null, string? note = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(code, yearNumb, monthNumb, dayNumb, note, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}