using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbContactTemps
{
    public class TbContactTempManager : TbContactTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbContactTempManager(ITbContactTempRepository tbContactTempRepository)
            : base(tbContactTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}