using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBranchImages
{
    public class TbCompanyBranchImageManager : TbCompanyBranchImageManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchImageManager(ITbCompanyBranchImageRepository tbCompanyBranchImageRepository)
            : base(tbCompanyBranchImageRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}