using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbUserMappingPersons
{
    public class TbUserMappingPersonManager : TbUserMappingPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingPersonManager(ITbUserMappingPersonRepository tbUserMappingPersonRepository)
            : base(tbUserMappingPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}