using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbUserMappingPersons
{
    public class TbUserMappingPerson : TbUserMappingPersonBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingPerson()
        {

        }

        public TbUserMappingPerson(int? userid = null, int? personid = null, bool? isActive = null)
            : base(userid, personid, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}