using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbLogSyncUats
{
    public class TbLogSyncUat : TbLogSyncUatBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogSyncUat()
        {

        }

        public TbLogSyncUat(DateTime timeExport, bool isSuccess, int userExport, string? reasonExportFailed = null)
            : base(timeExport, isSuccess, userExport, reasonExportFailed)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}