using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogSyncUats
{
    public class TbLogSyncUatManager : TbLogSyncUatManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogSyncUatManager(ITbLogSyncUatRepository tbLogSyncUatRepository)
            : base(tbLogSyncUatRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}