using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyMemberCouncilTerms
{
    public class TbCompanyMemberCouncilTermManager : TbCompanyMemberCouncilTermManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMemberCouncilTermManager(ITbCompanyMemberCouncilTermRepository tbCompanyMemberCouncilTermRepository)
            : base(tbCompanyMemberCouncilTermRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}