using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbContacts;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbContacts
{
    public class TbContactsAppService : TbContactsAppServiceBase, ITbContactsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbContactsAppService(ITbContactRepository tbContactRepository, TbContactManager tbContactManager, IDistributedCache<TbContactDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbContactRepository, tbContactManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbContactDto>> GetListNoPagedAsync(GetTbContactsInput input)
        {
            var items = await _tbContactRepository.GetListNoPagedAsync(input.FilterText, input.companyidMin, input.companyidMax, input.ContactName, input.ContactDept, input.ContactPosition, input.ContactEmail, input.ContactPhone, input.Note, input.DocStatusMin, input.DocStatusMax, input.IsActive, input.crt_userMin, input.crt_userMax, input.crt_dateMin, input.crt_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbContact>, List<TbContactDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}