using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbAdditionInfoTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbAdditionInfoTemps
{
    public class TbAdditionInfoTempsAppService : TbAdditionInfoTempsAppServiceBase, ITbAdditionInfoTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbAdditionInfoTempsAppService(ITbAdditionInfoTempRepository tbAdditionInfoTempRepository, TbAdditionInfoTempManager tbAdditionInfoTempManager, IDistributedCache<TbAdditionInfoTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbAdditionInfoTempRepository, tbAdditionInfoTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbAdditionInfoTempDto>> GetListNoPagedAsync(GetTbAdditionInfoTempsInput input)
        {
            var items = await _tbAdditionInfoTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.DocDateMin, input.DocDateMax, input.TypeOfGroup, input.TypeOfEvent, input.Description, input.NoOfDocument, input.Remark, input.IsActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbAdditionInfoTemp>, List<TbAdditionInfoTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}