using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TsClasses;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;
using Sabeco_Factsheet.TbCompanyPersons;

namespace Sabeco_Factsheet.TsClasses
{
    public class TsClassesAppService : TsClassesAppServiceBase, ITsClassesAppService
    {
        //<suite-custom-code-autogenerated>
        public TsClassesAppService(ITsClassRepository tsClassRepository, TsClassManager tsClassManager, IDistributedCache<TsClassDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tsClassRepository, tsClassManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TsClassDto>> GetListNoPagedAsync(GetTsClassesInput input)
        {
            var items = await _tsClassRepository.GetListNoPagedAsync(input.FilterText, input.ParentCode, input.Code, input.Name, input.Name_EN, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Code_Type, input.Sorting);

            return ObjectMapper.Map<List<TsClass>, List<TsClassDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
        public virtual async Task<List<TsClassDto>> GetListByParentCode(string parentCode)
        {
            var items = await _tsClassRepository.GetListByParentCode(parentCode);
            return ObjectMapper.Map<List<TsClass>, List<TsClassDto>>(items);
        }
    }
}