using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbStockPrices
{
    public class TbStockPriceManager : TbStockPriceManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbStockPriceManager(ITbStockPriceRepository tbStockPriceRepository)
            : base(tbStockPriceRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}