using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbStockPrices
{
    public class TbStockPrice : TbStockPriceBase
    {
        //<suite-custom-code-autogenerated>
        public TbStockPrice()
        {

        }

        public TbStockPrice(string stockCode, DateTime? stockDate = null, decimal? limitUpPrice = null, decimal? limitDownPrice = null, decimal? referencePrice = null, decimal? saleQty1 = null, decimal? salePrice1 = null, decimal? saleQty2 = null, decimal? salePrice2 = null, decimal? saleQty3 = null, decimal? salePrice3 = null, decimal? buyQty1 = null, decimal? buyPrice1 = null, decimal? buyQty2 = null, decimal? buyPrice2 = null, decimal? buyQty3 = null, decimal? buyPrice3 = null, decimal? transactionPrice = null, decimal? transactionQty = null, decimal? totalQty = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null)
            : base(stockCode, stockDate, limitUpPrice, limitDownPrice, referencePrice, saleQty1, salePrice1, saleQty2, salePrice2, saleQty3, salePrice3, buyQty1, buyPrice1, buyQty2, buyPrice2, buyQty3, buyPrice3, transactionPrice, transactionQty, totalQty, isActive, crt_date, crt_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}