using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbSkus
{
    public class TbSkuManager : TbSkuManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbSkuManager(ITbSkuRepository tbSkuRepository)
            : base(tbSkuRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}