using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbSkus
{
    public class TbSku : TbSkuBase
    {
        //<suite-custom-code-autogenerated>
        public TbSku()
        {

        }

        public TbSku(string? code = null, string? name = null, string? name_EN = null, string? brandCode = null, string? unit = null, string? itemBaseType = null, decimal? packSize = null, int? packQuantity = null, decimal? weight = null, int? expiryDate = null, bool? isActive = null, int? crt_user = null, DateTime? crt_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(code, name, name_EN, brandCode, unit, itemBaseType, packSize, packQuantity, weight, expiryDate, isActive, crt_user, crt_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}