using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbInvestPersons;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbInvestPersons
{
    public class TbInvestPersonsAppService : TbInvestPersonsAppServiceBase, ITbInvestPersonsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbInvestPersonsAppService(ITbInvestPersonRepository tbInvestPersonRepository, TbInvestPersonManager tbInvestPersonManager, IDistributedCache<TbInvestPersonDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbInvestPersonRepository, tbInvestPersonManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbInvestPersonDto>> GetListNoPagedAsync(GetTbInvestPersonsInput input)
        {
            var items = await _tbInvestPersonRepository.GetListNoPagedAsync(input.FilterText, input.ParentIdMin, input.ParentIdMax, input.PersonIdMin, input.PersonIdMax, input.FromDateMin, input.FromDateMax, input.PersonalValueMin, input.PersonalValueMax, input.OwnerValueMin, input.OwnerValueMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbInvestPerson>, List<TbInvestPersonDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}