using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyStockTemps
{
    public class TbCompanyStockTemp : TbCompanyStockTempBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyStockTemp()
        {

        }

        public TbCompanyStockTemp(int companyId, string companyCode, bool isPublicCompany, bool isActive, string? stockExchange = null, DateTime? registrationDate = null, decimal? charteredCapital = null, decimal? parValue = null, int? totalShare = null, int? listedShare = null, string? description = null, DateTime? crt_date = null, int? crt_user = null)
            : base(companyId, companyCode, isPublicCompany, isActive, stockExchange, registrationDate, charteredCapital, parValue, totalShare, listedShare, description, crt_date, crt_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}