using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyStockTemps
{
    public class TbCompanyStockTempManager : TbCompanyStockTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyStockTempManager(ITbCompanyStockTempRepository tbCompanyStockTempRepository)
            : base(tbCompanyStockTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}