using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbMenus
{
    public class TbMenuManager : TbMenuManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbMenuManager(ITbMenuRepository tbMenuRepository)
            : base(tbMenuRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}