using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyStockTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyStockTemps
{
    public class TbCompanyStockTempsAppService : TbCompanyStockTempsAppServiceBase, ITbCompanyStockTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyStockTempsAppService(ITbCompanyStockTempRepository tbCompanyStockTempRepository, TbCompanyStockTempManager tbCompanyStockTempManager, IDistributedCache<TbCompanyStockTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyStockTempRepository, tbCompanyStockTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyStockTempDto>> GetListNoPagedAsync(GetTbCompanyStockTempsInput input)
        {
            var items = await _tbCompanyStockTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.CompanyCode, input.IsPublicCompany, input.StockExchange, input.RegistrationDateMin, input.RegistrationDateMax, input.CharteredCapitalMin, input.CharteredCapitalMax, input.ParValueMin, input.ParValueMax, input.TotalShareMin, input.TotalShareMax, input.ListedShareMin, input.ListedShareMax, input.Description, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyStockTemp>, List<TbCompanyStockTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}