using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogSendEmailRetirements
{
    public class TbLogSendEmailRetirementManager : TbLogSendEmailRetirementManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogSendEmailRetirementManager(ITbLogSendEmailRetirementRepository tbLogSendEmailRetirementRepository)
            : base(tbLogSendEmailRetirementRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}