using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyBusinessDetailTemps
{
    public class TbCompanyBusinessDetailTemp : TbCompanyBusinessDetailTempBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessDetailTemp()
        {

        }

        public TbCompanyBusinessDetailTemp(int parentId, string registrationCode, string? registrationName = null, string? registrationName_EN = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(parentId, registrationCode, registrationName, registrationName_EN, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}