using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBusinessDetailTemps
{
    public class TbCompanyBusinessDetailTempManager : TbCompanyBusinessDetailTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessDetailTempManager(ITbCompanyBusinessDetailTempRepository tbCompanyBusinessDetailTempRepository)
            : base(tbCompanyBusinessDetailTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}