using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbInvestDetails
{
    public class TbInvestDetail : TbInvestDetailBase
    {
        //<suite-custom-code-autogenerated>
        public TbInvestDetail()
        {

        }

        public TbInvestDetail(int parentId, int investType, bool isDeleted, DateTime? docDate = null, string? docNo = null, int? shareNum = null, decimal? shareValue = null, string? note = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(parentId, investType, isDeleted, docDate, docNo, shareNum, shareValue, note, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}