using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TsClassTemps
{
    public class TsClassTempManager : TsClassTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TsClassTempManager(ITsClassTempRepository tsClassTempRepository)
            : base(tsClassTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}