using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbNationalityTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbNationalityTemps
{
    public class TbNationalityTempsAppService : TbNationalityTempsAppServiceBase, ITbNationalityTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbNationalityTempsAppService(ITbNationalityTempRepository tbNationalityTempRepository, TbNationalityTempManager tbNationalityTempManager, IDistributedCache<TbNationalityTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbNationalityTempRepository, tbNationalityTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbNationalityTempDto>> GetListNoPagedAsync(GetTbNationalityTempsInput input)
        {
            var items = await _tbNationalityTempRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.Code2, input.Name_en, input.Name_vn, input.IsActive, input.Sorting);

            return ObjectMapper.Map<List<TbNationalityTemp>, List<TbNationalityTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}