using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbUserMappingBreweries;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbUserMappingBreweries
{
    public class TbUserMappingBreweriesAppService : TbUserMappingBreweriesAppServiceBase, ITbUserMappingBreweriesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingBreweriesAppService(ITbUserMappingBreweryRepository tbUserMappingBreweryRepository, TbUserMappingBreweryManager tbUserMappingBreweryManager, IDistributedCache<TbUserMappingBreweryDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbUserMappingBreweryRepository, tbUserMappingBreweryManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbUserMappingBreweryDto>> GetListNoPagedAsync(GetTbUserMappingBreweriesInput input)
        {
            var items = await _tbUserMappingBreweryRepository.GetListNoPagedAsync(input.FilterText, input.useridMin, input.useridMax, input.breweryidMin, input.breweryidMax, input.IsActive, input.Sorting);

            return ObjectMapper.Map<List<TbUserMappingBrewery>, List<TbUserMappingBreweryDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}