using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbNationalities;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbNationalities
{
    public class TbNationalitiesAppService : TbNationalitiesAppServiceBase, ITbNationalitiesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbNationalitiesAppService(ITbNationalityRepository tbNationalityRepository, TbNationalityManager tbNationalityManager, IDistributedCache<TbNationalityDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbNationalityRepository, tbNationalityManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbNationalityDto>> GetListNoPagedAsync(GetTbNationalitiesInput input)
        {
            var items = await _tbNationalityRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.Code2, input.Name_en, input.Name_vn, input.IsActive, input.Sorting);

            return ObjectMapper.Map<List<TbNationality>, List<TbNationalityDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}