using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLandInfos;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLandInfos
{
    public class TbLandInfosAppService : TbLandInfosAppServiceBase, ITbLandInfosAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLandInfosAppService(ITbLandInfoRepository tbLandInfoRepository, TbLandInfoManager tbLandInfoManager, IDistributedCache<TbLandInfoDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLandInfoRepository, tbLandInfoManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLandInfoDto>> GetListNoPagedAsync(GetTbLandInfosInput input)
        {
            var items = await _tbLandInfoRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.Description, input.Address, input.TypeOfLand, input.AreaMin, input.AreaMax, input.SupportingDocument, input.IssueDateMin, input.IssueDateMax, input.ExpiryDateMin, input.ExpiryDateMax, input.Payment, input.Remark, input.IsActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbLandInfo>, List<TbLandInfoDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}