using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbHisCompanyPersons;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbHisCompanyPersons
{
    public class TbHisCompanyPersonsAppService : TbHisCompanyPersonsAppServiceBase, ITbHisCompanyPersonsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbHisCompanyPersonsAppService(ITbHisCompanyPersonRepository tbHisCompanyPersonRepository, TbHisCompanyPersonManager tbHisCompanyPersonManager, IDistributedCache<TbHisCompanyPersonDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbHisCompanyPersonRepository, tbHisCompanyPersonManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbHisCompanyPersonDto>> GetListNoPagedAsync(GetTbHisCompanyPersonsInput input)
        {
            var items = await _tbHisCompanyPersonRepository.GetListNoPagedAsync(input.FilterText, input.IsSendMail, input.DateSendMailMin, input.DateSendMailMax, input.InsertDateMin, input.InsertDateMax, input.TypeMin, input.TypeMax, input.BranchCode, input.IdCompanyPersonMin, input.IdCompanyPersonMax, input.CompanyIdMin, input.CompanyIdMax, input.PersonIdMin, input.PersonIdMax, input.FromDateMin, input.FromDateMax, input.ToDateMin, input.ToDateMax, input.PositionIdMin, input.PositionIdMax, input.PositionCode, input.PersonalValueMin, input.PersonalValueMax, input.PersonalSharePercentageMin, input.PersonalSharePercentageMax, input.OwnerValueMin, input.OwnerValueMax, input.RepresentativePercentageMin, input.RepresentativePercentageMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbHisCompanyPerson>, List<TbHisCompanyPersonDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}