using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbConfigRetirementTimes;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbConfigRetirementTimes
{
    public class TbConfigRetirementTimesAppService : TbConfigRetirementTimesAppServiceBase, ITbConfigRetirementTimesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbConfigRetirementTimesAppService(ITbConfigRetirementTimeRepository tbConfigRetirementTimeRepository, TbConfigRetirementTimeManager tbConfigRetirementTimeManager, IDistributedCache<TbConfigRetirementTimeDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbConfigRetirementTimeRepository, tbConfigRetirementTimeManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbConfigRetirementTimeDto>> GetListNoPagedAsync(GetTbConfigRetirementTimesInput input)
        {
            var items = await _tbConfigRetirementTimeRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.YearNumbMin, input.YearNumbMax, input.MonthNumbMin, input.MonthNumbMax, input.DayNumbMin, input.DayNumbMax, input.Note, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbConfigRetirementTime>, List<TbConfigRetirementTimeDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}