using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyStocks
{
    public class TbCompanyStockManager : TbCompanyStockManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyStockManager(ITbCompanyStockRepository tbCompanyStockRepository)
            : base(tbCompanyStockRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}