using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbBranchs
{
    public class TbBranch : TbBranchBase
    {
        //<suite-custom-code-autogenerated>
        public TbBranch()
        {

        }

        public TbBranch(string code, string name, bool isActive, string? briefName = null, string? name_EN = null, string? companyCode = null, string? description = null, DateTime? crt_Date = null)
            : base(code, name, isActive, briefName, name_EN, companyCode, description, crt_Date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}