using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBranchs
{
    public class TbBranchManager : TbBranchManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBranchManager(ITbBranchRepository tbBranchRepository)
            : base(tbBranchRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}