using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyPersonTemps
{
    public class TbCompanyPersonTempManager : TbCompanyPersonTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyPersonTempManager(ITbCompanyPersonTempRepository tbCompanyPersonTempRepository)
            : base(tbCompanyPersonTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}