using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbTerms;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbTerms
{
    public class TbTermsAppService : TbTermsAppServiceBase, ITbTermsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbTermsAppService(ITbTermRepository tbTermRepository, TbTermManager tbTermManager, IDistributedCache<TbTermDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbTermRepository, tbTermManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbTermDto>> GetListNoPagedAsync(GetTbTermsInput input)
        {
            var items = await _tbTermRepository.GetListNoPagedAsync(input.FilterText, input.BranchIdMin, input.BranchIdMax, input.TermCode, input.FromYearMin, input.FromYearMax, input.ToYearMin, input.ToYearMax, input.Description, input.Sorting);

            return ObjectMapper.Map<List<TbTerm>, List<TbTermDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}