using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbHisLogPrintings
{
    public class TbHisLogPrintingManager : TbHisLogPrintingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisLogPrintingManager(ITbHisLogPrintingRepository tbHisLogPrintingRepository)
            : base(tbHisLogPrintingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}