using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbHisLogPrintings
{
    public class TbHisLogPrinting : TbHisLogPrintingBase
    {
        //<suite-custom-code-autogenerated>
        public TbHisLogPrinting()
        {

        }

        public TbHisLogPrinting(DateTime insertDate, bool? isSendMail = null, DateTime? dateSendMail = null, int? type = null, string? userName = null, string? companyCode = null, string? fileLanguage = null, bool? isPrinting = null)
            : base(insertDate, isSendMail, dateSendMail, type, userName, companyCode, fileLanguage, isPrinting)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}