using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbInvestPersons
{
    public class TbInvestPersonManager : TbInvestPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbInvestPersonManager(ITbInvestPersonRepository tbInvestPersonRepository)
            : base(tbInvestPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}