using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;
using Volo.Abp.Domain.Entities;

using Volo.Abp;

namespace Sabeco_Factsheet.TbInvestPersons
{
    public class TbInvestPerson : TbInvestPersonBase
    {
        //<suite-custom-code-autogenerated>
        public TbInvestPerson()
        {

        }

        public TbInvestPerson(int parentId, int personId, DateTime fromDate, bool isDeleted, int? personalValue = null, int? ownerValue = null, string? note = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(parentId, personId, fromDate, isDeleted, personalValue, ownerValue, note, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}