using Sabeco_Factsheet.TbBrewerySkuTemps;
using Xunit;

namespace Sabeco_Factsheet.EntityFrameworkCore.Applications.TbBrewerySkuTemps;

public class EfCoreTbBrewerySkuTempsAppServiceTests : TbBrewerySkuTempsAppServiceTests<Sabeco_FactsheetEntityFrameworkCoreTestModule>
{
}