using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBusinesses
{
    public class TbCompanyBusinessManager : TbCompanyBusinessManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessManager(ITbCompanyBusinessRepository tbCompanyBusinessRepository)
            : base(tbCompanyBusinessRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}