using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyBusinesses
{
    public class TbCompanyBusiness : TbCompanyBusinessBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusiness()
        {

        }

        public TbCompanyBusiness(int companyId, byte registrationNo, DateTime registrationDate, string? license = null, string? companyName = null, string? companyAddress = null, string? legalRepresent = null, string? companyType = null, string? majorBusiness = null, string? otherActivity = null, string? note = null, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null, DateTime? latestAmendment = null)
            : base(companyId, registrationNo, registrationDate, license, companyName, companyAddress, legalRepresent, companyType, majorBusiness, otherActivity, note, isActive, crt_date, crt_user, mod_date, mod_user, latestAmendment)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}