using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyMappings
{
    public class TbCompanyMapping : TbCompanyMappingBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMapping()
        {

        }

        public TbCompanyMapping(int? companyId = null, string? companyTypeShareholdingCode = null, string? companyTypesCode = null, string? note = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null, int? idCompanyTypeShareholdingCode = null, int? idCompanyTypesCode = null)
            : base(companyId, companyTypeShareholdingCode, companyTypesCode, note, crt_date, crt_user, mod_date, mod_user, idCompanyTypeShareholdingCode, idCompanyTypesCode)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}