using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyMappings
{
    public class TbCompanyMappingManager : TbCompanyMappingManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMappingManager(ITbCompanyMappingRepository tbCompanyMappingRepository)
            : base(tbCompanyMappingRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}