using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogSendEmails;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogSendEmails
{
    public class TbLogSendEmailsAppService : TbLogSendEmailsAppServiceBase, ITbLogSendEmailsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogSendEmailsAppService(ITbLogSendEmailRepository tbLogSendEmailRepository, TbLogSendEmailManager tbLogSendEmailManager, IDistributedCache<TbLogSendEmailDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogSendEmailRepository, tbLogSendEmailManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogSendEmailDto>> GetListNoPagedAsync(GetTbLogSendEmailsInput input)
        {
            var items = await _tbLogSendEmailRepository.GetListNoPagedAsync(input.FilterText, input.TimeSendMin, input.TimeSendMax, input.IsSuccess, input.UserSend, input.TypeEmail, input.FailedReason, input.Sorting);

            return ObjectMapper.Map<List<TbLogSendEmail>, List<TbLogSendEmailDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}