using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbBreweryImages;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbBreweryImages
{
    public class TbBreweryImagesAppService : TbBreweryImagesAppServiceBase, ITbBreweryImagesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryImagesAppService(ITbBreweryImageRepository tbBreweryImageRepository, TbBreweryImageManager tbBreweryImageManager, IDistributedCache<TbBreweryImageDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbBreweryImageRepository, tbBreweryImageManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbBreweryImageDto>> GetListNoPagedAsync(GetTbBreweryImagesInput input)
        {
            var items = await _tbBreweryImageRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.BreweryImage, input.ImageLink, input.isActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbBreweryImage>, List<TbBreweryImageDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}