using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbRoles;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbRoles
{
    public class TbRolesAppService : TbRolesAppServiceBase, ITbRolesAppService
    {
        //<suite-custom-code-autogenerated>
        public TbRolesAppService(ITbRoleRepository tbRoleRepository, TbRoleManager tbRoleManager, IDistributedCache<TbRoleDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbRoleRepository, tbRoleManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbRoleDto>> GetListNoPagedAsync(GetTbRolesInput input)
        {
            var items = await _tbRoleRepository.GetListNoPagedAsync(input.FilterText, input.Code, input.Name, input.Description, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbRole>, List<TbRoleDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}