using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbFileUploadTemps
{
    public class TbFileUploadTempManager : TbFileUploadTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbFileUploadTempManager(ITbFileUploadTempRepository tbFileUploadTempRepository)
            : base(tbFileUploadTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}