using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbAssets;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbAssets
{
    public class TbAssetsAppService : TbAssetsAppServiceBase, ITbAssetsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbAssetsAppService(ITbAssetRepository tbAssetRepository, TbAssetManager tbAssetManager, IDistributedCache<TbAssetDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbAssetRepository, tbAssetManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbAssetDto>> GetListNoPagedAsync(GetTbAssetsInput input)
        {
            var items = await _tbAssetRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.AssetType, input.AssetItem, input.AssetAddress, input.QuantityMin, input.QuantityMax, input.DocNo, input.DocDateMin, input.DocDateMax, input.ExpireDateMin, input.ExpireDateMax, input.Description, input.DocStatusMin, input.DocStatusMax, input.IsActive, input.IsDeleted, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbAsset>, List<TbAssetDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}