using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyBoards
{
    public class TbCompanyBoard : TbCompanyBoardBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBoard()
        {

        }

        public TbCompanyBoard(string companyCode, string personCode, bool isActive, bool isDeleted, string? branchCode = null, DateTime? fromDate = null, DateTime? toDate = null, string? positionCode = null, int? personalValue = null, int? ownerValue = null, string? note = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(companyCode, personCode, isActive, isDeleted, branchCode, fromDate, toDate, positionCode, personalValue, ownerValue, note, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}