using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBoards
{
    public class TbCompanyBoardManager : TbCompanyBoardManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBoardManager(ITbCompanyBoardRepository tbCompanyBoardRepository)
            : base(tbCompanyBoardRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}