using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbBreweries
{
    public class TbBreweryManager : TbBreweryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbBreweryManager(ITbBreweryRepository tbBreweryRepository)
            : base(tbBreweryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}