using System;

namespace Sabeco_Factsheet.TbCompanyBusinessDetailTemps;

[Serializable]
public class TbCompanyBusinessDetailTempDownloadTokenCacheItem : TbCompanyBusinessDetailTempDownloadTokenCacheItemBase
{
}