using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBusinessDetailTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBusinessDetailTemps
{
    public class TbCompanyBusinessDetailTempsAppService : TbCompanyBusinessDetailTempsAppServiceBase, ITbCompanyBusinessDetailTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessDetailTempsAppService(ITbCompanyBusinessDetailTempRepository tbCompanyBusinessDetailTempRepository, TbCompanyBusinessDetailTempManager tbCompanyBusinessDetailTempManager, IDistributedCache<TbCompanyBusinessDetailTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBusinessDetailTempRepository, tbCompanyBusinessDetailTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBusinessDetailTempDto>> GetListNoPagedAsync(GetTbCompanyBusinessDetailTempsInput input)
        {
            var items = await _tbCompanyBusinessDetailTempRepository.GetListNoPagedAsync(input.FilterText, input.ParentIdMin, input.ParentIdMax, input.RegistrationCode, input.RegistrationName, input.RegistrationName_EN, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBusinessDetailTemp>, List<TbCompanyBusinessDetailTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}