using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyMajorTemps
{
    public class TbCompanyMajorTempManager : TbCompanyMajorTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMajorTempManager(ITbCompanyMajorTempRepository tbCompanyMajorTempRepository)
            : base(tbCompanyMajorTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}