using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLogRefeshAccounts
{
    public class TbLogRefeshAccountManager : TbLogRefeshAccountManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLogRefeshAccountManager(ITbLogRefeshAccountRepository tbLogRefeshAccountRepository)
            : base(tbLogRefeshAccountRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}