using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbRoles
{
    public class TbRoleManager : TbRoleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbRoleManager(ITbRoleRepository tbRoleRepository)
            : base(tbRoleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}