using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanies
{
    public class TbCompanyManager : TbCompanyManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyManager(ITbCompanyRepository tbCompanyRepository)
            : base(tbCompanyRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}