using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbAdditionInfoTemps
{
    public class TbAdditionInfoTempManager : TbAdditionInfoTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbAdditionInfoTempManager(ITbAdditionInfoTempRepository tbAdditionInfoTempRepository)
            : base(tbAdditionInfoTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}