using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbUserMappingBreweries
{
    public class TbUserMappingBrewery : TbUserMappingBreweryBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingBrewery()
        {

        }

        public TbUserMappingBrewery(int? userid = null, int? breweryid = null, bool? isActive = null)
            : base(userid, breweryid, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}