using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbUserMappingBreweries
{
    public class TbUserMappingBreweryManager : TbUserMappingBreweryManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserMappingBreweryManager(ITbUserMappingBreweryRepository tbUserMappingBreweryRepository)
            : base(tbUserMappingBreweryRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}