using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBusinessTemps
{
    public class TbCompanyBusinessTempManager : TbCompanyBusinessTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessTempManager(ITbCompanyBusinessTempRepository tbCompanyBusinessTempRepository)
            : base(tbCompanyBusinessTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}