using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbAdditionInfos
{
    public class TbAdditionInfo : TbAdditionInfoBase
    {
        //<suite-custom-code-autogenerated>
        public TbAdditionInfo()
        {

        }

        public TbAdditionInfo(int companyId, DateTime? docDate = null, string? typeOfGroup = null, string? typeOfEvent = null, string? description = null, string? noOfDocument = null, string? remark = null, bool? isActive = null, int? create_user = null, DateTime? create_date = null, int? mod_user = null, DateTime? mod_date = null)
            : base(companyId, docDate, typeOfGroup, typeOfEvent, description, noOfDocument, remark, isActive, create_user, create_date, mod_user, mod_date)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}