using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbAdditionInfos
{
    public class TbAdditionInfoManager : TbAdditionInfoManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbAdditionInfoManager(ITbAdditionInfoRepository tbAdditionInfoRepository)
            : base(tbAdditionInfoRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}