using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbFileUploads;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbFileUploads
{
    public class TbFileUploadsAppService : TbFileUploadsAppServiceBase, ITbFileUploadsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbFileUploadsAppService(ITbFileUploadRepository tbFileUploadRepository, TbFileUploadManager tbFileUploadManager, IDistributedCache<TbFileUploadDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbFileUploadRepository, tbFileUploadManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbFileUploadDto>> GetListNoPagedAsync(GetTbFileUploadsInput input)
        {
            var items = await _tbFileUploadRepository.GetListNoPagedAsync(input.FilterText, input.companyIdMin, input.companyIdMax, input.personIdMin, input.personIdMax, input.fileName, input.fullFileName, input.fileLink, input.uploadDateMin, input.uploadDateMax, input.UserUploadMin, input.UserUploadMax, input.note, input.IsActive, input.DownloadCountMin, input.DownloadCountMax, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.Sorting);

            return ObjectMapper.Map<List<TbFileUpload>, List<TbFileUploadDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}