using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbLogSendEmailRetirements;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbLogSendEmailRetirements
{
    public class TbLogSendEmailRetirementsAppService : TbLogSendEmailRetirementsAppServiceBase, ITbLogSendEmailRetirementsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbLogSendEmailRetirementsAppService(ITbLogSendEmailRetirementRepository tbLogSendEmailRetirementRepository, TbLogSendEmailRetirementManager tbLogSendEmailRetirementManager, IDistributedCache<TbLogSendEmailRetirementDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbLogSendEmailRetirementRepository, tbLogSendEmailRetirementManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbLogSendEmailRetirementDto>> GetListNoPagedAsync(GetTbLogSendEmailRetirementsInput input)
        {
            var items = await _tbLogSendEmailRetirementRepository.GetListNoPagedAsync(input.FilterText, input.idCompanyMin, input.idCompanyMax, input.idPersonMin, input.idPersonMax, input.IsSendEmail, input.DateSendEmailMin, input.DateSendEmailMax, input.TypeMin, input.TypeMax, input.Sorting);

            return ObjectMapper.Map<List<TbLogSendEmailRetirement>, List<TbLogSendEmailRetirementDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}