using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbMenus;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbMenus
{
    public class TbMenusAppService : TbMenusAppServiceBase, ITbMenusAppService
    {
        //<suite-custom-code-autogenerated>
        public TbMenusAppService(ITbMenuRepository tbMenuRepository, TbMenuManager tbMenuManager, IDistributedCache<TbMenuDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbMenuRepository, tbMenuManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbMenuDto>> GetListNoPagedAsync(GetTbMenusInput input)
        {
            var items = await _tbMenuRepository.GetListNoPagedAsync(input.FilterText, input.ControlName, input.Description, input.IsActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbMenu>, List<TbMenuDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}