using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyPersons
{
    public class TbCompanyPerson : TbCompanyPersonBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyPerson()
        {

        }

        public TbCompanyPerson(int companyId, int personId, bool isActive, bool isDeleted, string? branchCode = null, int? positionId = null, DateTime? fromDate = null, DateTime? toDate = null, string? positionCode = null, byte? postionType = null, decimal? personalValue = null, decimal? personalSharePercentage = null, decimal? ownerValue = null, decimal? representativePercentage = null, string? note = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(companyId, personId, isActive, isDeleted, branchCode, positionId, fromDate, toDate, positionCode, postionType, personalValue, personalSharePercentage, ownerValue, representativePercentage, note, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}