using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyPersons
{
    public class TbCompanyPersonManager : TbCompanyPersonManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyPersonManager(ITbCompanyPersonRepository tbCompanyPersonRepository)
            : base(tbCompanyPersonRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}