using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBusinessTemps;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBusinessTemps
{
    public class TbCompanyBusinessTempsAppService : TbCompanyBusinessTempsAppServiceBase, ITbCompanyBusinessTempsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessTempsAppService(ITbCompanyBusinessTempRepository tbCompanyBusinessTempRepository, TbCompanyBusinessTempManager tbCompanyBusinessTempManager, IDistributedCache<TbCompanyBusinessTempDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBusinessTempRepository, tbCompanyBusinessTempManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBusinessTempDto>> GetListNoPagedAsync(GetTbCompanyBusinessTempsInput input)
        {
            var items = await _tbCompanyBusinessTempRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.License, input.RegistrationNoMin, input.RegistrationNoMax, input.RegistrationDateMin, input.RegistrationDateMax, input.CompanyName, input.CompanyAddress, input.LegalRepresent, input.CompanyType, input.MajorBusiness, input.OtherActivity, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.LatestAmendmentMin, input.LatestAmendmentMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBusinessTemp>, List<TbCompanyBusinessTempDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}