using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbCompanyInvests
{
    public class TbCompanyInvest : TbCompanyInvestBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyInvest()
        {

        }

        public TbCompanyInvest(int companyId, bool isActive, bool isDeleted, string? companyName = null, decimal? shares = null, decimal? holding = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(companyId, isActive, isDeleted, companyName, shares, holding, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}