using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyInvests
{
    public class TbCompanyInvestManager : TbCompanyInvestManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyInvestManager(ITbCompanyInvestRepository tbCompanyInvestRepository)
            : base(tbCompanyInvestRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}