using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbHisLogPrintings;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbHisLogPrintings
{
    public class TbHisLogPrintingsAppService : TbHisLogPrintingsAppServiceBase, ITbHisLogPrintingsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbHisLogPrintingsAppService(ITbHisLogPrintingRepository tbHisLogPrintingRepository, TbHisLogPrintingManager tbHisLogPrintingManager, IDistributedCache<TbHisLogPrintingDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbHisLogPrintingRepository, tbHisLogPrintingManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbHisLogPrintingDto>> GetListNoPagedAsync(GetTbHisLogPrintingsInput input)
        {
            var items = await _tbHisLogPrintingRepository.GetListNoPagedAsync(input.FilterText, input.IsSendMail, input.DateSendMailMin, input.DateSendMailMax, input.TypeMin, input.TypeMax, input.InsertDateMin, input.InsertDateMax, input.UserName, input.CompanyCode, input.FileLanguage, input.IsPrinting, input.Sorting);

            return ObjectMapper.Map<List<TbHisLogPrinting>, List<TbHisLogPrintingDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}