using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbLandInfoTemps
{
    public class TbLandInfoTempManager : TbLandInfoTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbLandInfoTempManager(ITbLandInfoTempRepository tbLandInfoTempRepository)
            : base(tbLandInfoTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}