using System;

namespace Sabeco_Factsheet.TbBreweryDeliveryVolumeTemps;

[Serializable]
public class TbBreweryDeliveryVolumeTempDownloadTokenCacheItem : TbBreweryDeliveryVolumeTempDownloadTokenCacheItemBase
{
}