using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBranchs;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBranchs
{
    public class TbCompanyBranchsAppService : TbCompanyBranchsAppServiceBase, ITbCompanyBranchsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBranchsAppService(ITbCompanyBranchRepository tbCompanyBranchRepository, TbCompanyBranchManager tbCompanyBranchManager, IDistributedCache<TbCompanyBranchDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBranchRepository, tbCompanyBranchManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBranchDto>> GetListNoPagedAsync(GetTbCompanyBranchsInput input)
        {
            var items = await _tbCompanyBranchRepository.GetListNoPagedAsync(input.FilterText, input.CompanyIdMin, input.CompanyIdMax, input.BranchName, input.BranchAddress, input.BranchCode, input.ContactPerson, input.ContactPhone, input.Email, input.isActive, input.create_userMin, input.create_userMax, input.create_dateMin, input.create_dateMax, input.mod_userMin, input.mod_userMax, input.mod_dateMin, input.mod_dateMax, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBranch>, List<TbCompanyBranchDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}