using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyBusinessDetails
{
    public class TbCompanyBusinessDetailManager : TbCompanyBusinessDetailManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBusinessDetailManager(ITbCompanyBusinessDetailRepository tbCompanyBusinessDetailRepository)
            : base(tbCompanyBusinessDetailRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}