using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbCompanyMappingTemps
{
    public class TbCompanyMappingTempManager : TbCompanyMappingTempManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyMappingTempManager(ITbCompanyMappingTempRepository tbCompanyMappingTempRepository)
            : base(tbCompanyMappingTempRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}