using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbUserInRoles
{
    public class TbUserInRole : TbUserInRoleBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserInRole()
        {

        }

        public TbUserInRole(int roleId, int userId, bool? isActive = null, DateTime? crt_date = null, int? crt_user = null, DateTime? mod_date = null, int? mod_user = null)
            : base(roleId, userId, isActive, crt_date, crt_user, mod_date, mod_user)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}