using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbUserInRoles
{
    public class TbUserInRoleManager : TbUserInRoleManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbUserInRoleManager(ITbUserInRoleRepository tbUserInRoleRepository)
            : base(tbUserInRoleRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}