using System;
using System.IO;
using System.Linq;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Linq.Dynamic.Core;
using Microsoft.AspNetCore.Authorization;
using Volo.Abp;
using Volo.Abp.Application.Dtos;
using Volo.Abp.Application.Services;
using Volo.Abp.Domain.Repositories;
using Sabeco_Factsheet.Permissions;
using Sabeco_Factsheet.TbCompanyBoards;
using MiniExcelLibs;
using Volo.Abp.Content;
using Volo.Abp.Authorization;
using Volo.Abp.Caching;
using Microsoft.Extensions.Caching.Distributed;
using Sabeco_Factsheet.Shared;

namespace Sabeco_Factsheet.TbCompanyBoards
{
    public class TbCompanyBoardsAppService : TbCompanyBoardsAppServiceBase, ITbCompanyBoardsAppService
    {
        //<suite-custom-code-autogenerated>
        public TbCompanyBoardsAppService(ITbCompanyBoardRepository tbCompanyBoardRepository, TbCompanyBoardManager tbCompanyBoardManager, IDistributedCache<TbCompanyBoardDownloadTokenCacheItem, string> downloadTokenCache)
            : base(tbCompanyBoardRepository, tbCompanyBoardManager, downloadTokenCache)
        {
        }
        //HQSOFT's generated code:
        public virtual async Task<List<TbCompanyBoardDto>> GetListNoPagedAsync(GetTbCompanyBoardsInput input)
        {
            var items = await _tbCompanyBoardRepository.GetListNoPagedAsync(input.FilterText, input.BranchCode, input.CompanyCode, input.PersonCode, input.FromDateMin, input.FromDateMax, input.ToDateMin, input.ToDateMax, input.PositionCode, input.PersonalValueMin, input.PersonalValueMax, input.OwnerValueMin, input.OwnerValueMax, input.Note, input.IsActive, input.crt_dateMin, input.crt_dateMax, input.crt_userMin, input.crt_userMax, input.mod_dateMin, input.mod_dateMax, input.mod_userMin, input.mod_userMax, input.IsDeleted, input.Sorting);

            return ObjectMapper.Map<List<TbCompanyBoard>, List<TbCompanyBoardDto>>(items);
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}