using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbNationalities
{
    public class TbNationalityManager : TbNationalityManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbNationalityManager(ITbNationalityRepository tbNationalityRepository)
            : base(tbNationalityRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}