using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbNationalities
{
    public class TbNationality : TbNationalityBase
    {
        //<suite-custom-code-autogenerated>
        public TbNationality()
        {

        }

        public TbNationality(string? code = null, string? code2 = null, string? name_en = null, string? name_vn = null, bool? isActive = null)
            : base(code, code2, name_en, name_vn, isActive)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}