using System;
using Volo.Abp.Domain.Services;
using Volo.Abp.Domain.Repositories;

namespace Sabeco_Factsheet.TbTerms
{
    public class TbTermManager : TbTermManagerBase
    {
        //<suite-custom-code-autogenerated>
        public TbTermManager(ITbTermRepository tbTermRepository)
            : base(tbTermRepository)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}