using System;
using System.Linq;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using Volo.Abp.Domain.Entities;
using Volo.Abp.Domain.Entities.Auditing;
using Volo.Abp.MultiTenancy;
using JetBrains.Annotations;

using Volo.Abp;

namespace Sabeco_Factsheet.TbTerms
{
    public class TbTerm : TbTermBase
    {
        //<suite-custom-code-autogenerated>
        public TbTerm()
        {

        }

        public TbTerm(int branchId, string termCode, int? fromYear = null, int? toYear = null, string? description = null)
            : base(branchId, termCode, fromYear, toYear, description)
        {
        }
        //</suite-custom-code-autogenerated>

        //Write your custom code...
    }
}